import { useCallback } from 'react'
import { useDirection } from '../../contexts/DirectionContext'

/**
 * The widget settings panel's own words, in Arabic.
 *
 * The panel (WidgetConfigPanel.tsx) writes its labels in English at each call
 * site: tests find fields by them, ids are built from them, and the settings
 * search matches them. So the English text is the key, and only what is shown
 * is translated, through `usePanelLabel()`. Field names, option values and
 * anything read from the data are never passed through it.
 *
 * A label missing here shows in English; panelLabels.test.ts walks the panel's
 * source and fails when one is missing, so a new label is translated in the
 * same change that adds it. `{name}` placeholders are filled from `vars`.
 */
export const PANEL_AR: Record<string, string> = {
  // Frame
  '{type} settings': 'إعدادات {type}',
  'Filter settings': 'تصفية الإعدادات',
  'Filter settings…': 'ابحث في الإعدادات…',
  'Searching all tabs — clear the box to return to {tab}.': 'البحث في كل الأقسام — امسح المربع للعودة إلى {tab}.',
  'Settings sections': 'أقسام الإعدادات',
  'No {tab} settings for this object.': 'لا توجد إعدادات {tab} لهذا العنصر.',
  'All': 'الكل',
  'Options': 'الخيارات',
  'Data': 'البيانات',
  'Data roles': 'أدوار البيانات',
  'Actions': 'الإجراءات',
  'Display rules': 'قواعد العرض',
  'Filters': 'عوامل التصفية',
  'Ranks': 'الترتيب',
  'Object': 'العنصر',
  'Assign data': 'إسناد البيانات',

  // Widget types (the panel heading)
  'Bar': 'أعمدة', 'Line': 'خط', 'Pie': 'دائري', 'Donut': 'حلقي', 'Scatter': 'انتشار',
  'Treemap': 'خريطة شجرية', 'Step': 'درجات', 'Dot plot': 'مخطط نقطي', 'Needle': 'إبري',
  'Histogram': 'مدرج تكراري', 'Butterfly': 'فراشة', 'Dual axis bar': 'أعمدة بمحورين',
  'Dual axis line': 'خط بمحورين', 'Dual axis bar line': 'أعمدة وخط بمحورين',
  'Dual axis time series': 'سلسلة زمنية بمحورين', 'Comparative time series': 'سلسلة زمنية مقارنة',
  'Numeric series': 'سلسلة رقمية', 'Bubble': 'فقاعات', 'Bubble change': 'تغير الفقاعات',
  'Correlation matrix': 'مصفوفة الارتباط', 'Heatmap': 'خريطة حرارية',
  'Parallel coordinates': 'إحداثيات متوازية', 'Box plot': 'مخطط صندوقي', 'Waterfall': 'شلال',
  'Gauge': 'مقياس', 'Schedule': 'جدول زمني', 'Vector plot': 'مخطط متجهات', 'Word cloud': 'سحابة كلمات',
  'KPI': 'مؤشر أداء', 'Table': 'جدول', 'Crosstab': 'جدول متقاطع', 'List': 'قائمة', 'Text': 'نص',
  'Button': 'زر', 'Slicer': 'مُقسِّم', 'Area': 'مساحي', 'Funnel': 'قمع', 'Ribbon': 'شريطي',
  'Card': 'بطاقة', 'Matrix': 'مصفوفة', 'Image': 'صورة', 'Shape': 'شكل', 'Web content': 'محتوى ويب',
  'Custom visual': 'مرئي مخصص', 'Map choropleth': 'خريطة مظللة', 'Map points': 'خريطة نقاط',
  'Map bubbles': 'خريطة فقاعات', 'Map lines': 'خريطة خطوط', 'Map clusters': 'خريطة تجمعات',
  'Map pie': 'خريطة دوائر', 'Map layers': 'خريطة طبقات', 'Map density': 'خريطة كثافة',
  'Map network': 'خريطة شبكة', 'Map contour': 'خريطة كنتورية', 'Network': 'شبكة',
  'Container': 'حاوية', 'Forecast': 'تنبؤ', 'Sankey': 'سانكي', 'Decomposition': 'تحليل التفكيك',
  'Small multiples': 'مضاعفات صغيرة', 'Script': 'نص برمجي', 'Tree': 'شجرة', 'Sunburst': 'شمسي',
  'Icicle': 'جليدي', 'Dendrogram': 'شجرة تصنيف', 'Org': 'هيكل تنظيمي', 'Circle pack': 'دوائر متداخلة',
  'Custom graph': 'رسم مخصص', 'Model linear': 'نموذج خطي', 'Model logistic': 'نموذج لوجستي',
  'Model tree': 'نموذج شجرة قرار', 'Model cluster': 'نموذج تجميع', 'Model compare': 'مقارنة النماذج',
  'Model score': 'تقييم النموذج', 'Model rules': 'قواعد النموذج',

  // Object
  'Dataset': 'مجموعة البيانات',
  '{name} (default)': '{name} (الافتراضي)',
  '— report default —': '— افتراضي التقرير —',
  'Title': 'العنوان',
  'Widget title': 'عنوان العنصر',
  'Subtitle': 'العنوان الفرعي',
  'Optional — e.g. Share of total · all time': 'اختياري — مثل: الحصة من الإجمالي · كل الفترات',
  'RTL (Right to Left)': 'من اليمين إلى اليسار',
  'Content': 'المحتوى',
  'Enter text…': 'اكتب النص…',
  'Button label': 'نص الزر',
  'Image URL': 'رابط الصورة',
  'Image alt text': 'النص البديل للصورة',
  'Fit': 'الملاءمة',
  'Contain': 'احتواء',
  'Cover': 'تغطية',
  'Fill': 'ملء',
  'Web page URL': 'رابط صفحة الويب',
  'Embedded in a sandboxed frame. Only http(s) URLs load; some sites block being framed.': 'تُعرض داخل إطار معزول. تُحمَّل روابط http(s) فقط، وبعض المواقع تمنع عرضها داخل إطار.',
  'Visualisation URL': 'رابط المرئي',
  "A sandboxed page that receives this widget's data via": 'صفحة معزولة تستقبل بيانات هذا العنصر عبر',
  '). Bind a dimension/measure below to choose the data. Build one with the SDK,': '). اربط بُعدًا/مقياسًا أدناه لاختيار البيانات. أنشئ صفحة بحزمة التطوير،',
  'is a working example.': 'مثال يعمل.',
  'Transparent background': 'خلفية شفافة',
  "No panel and no border, so the page's background image shows through.": 'بلا لوحة ولا حدود، فتظهر صورة خلفية الصفحة من خلاله.',
  'Total in the centre': 'الإجمالي في المنتصف',
  'Caption under the total': 'تسمية تحت الإجمالي',
  "defaults to the measure's name": 'افتراضيًا اسم المقياس',
  "Runs on the server over this widget's own filtered, row- and column-secured frame, which arrives as": 'يعمل على الخادم فوق بيانات هذا العنصر بعد التصفية وتطبيق أمان الصفوف والأعمدة، وتصل باسم',
  '. Assign what the tile should show to': '. أسند ما يجب أن يعرضه العنصر إلى',
  '— a DataFrame, a Series or a single number.': '— إطار بيانات أو سلسلة أو رقم واحد.',
  'output is shown under the table.': 'يظهر ناتجه تحت الجدول.',
  "Only an organisation admin can save a script tile: this is code running on the server, in a separate process with no access to the application's credentials, but with whatever access the server itself has.": 'لا يحفظ عنصر النص البرمجي إلا مسؤول المؤسسة: فهو شيفرة تعمل على الخادم في عملية منفصلة لا تصل إلى بيانات اعتماد التطبيق، لكن لها كل صلاحيات الخادم نفسه.',
  'Rectangle': 'مستطيل',
  'Rounded rectangle': 'مستطيل بزوايا مستديرة',
  'Circle / Oval': 'دائرة / بيضاوي',
  'Border': 'الحدود',
  'Container style': 'نمط الحاوية',
  'Group (fixed layout)': 'مجموعة (تخطيط ثابت)',
  'Tabs (one child at a time)': 'علامات تبويب (عنصر واحد في كل مرة)',
  'Scrolling': 'تمرير',
  'Collapsible': 'قابلة للطي',
  'Precision (free positioning, overlapping)': 'دقيق (موضع حر مع تداخل)',
  'Background image': 'صورة الخلفية',
  'https://… floorplan or schematic': 'https://… مخطط طابق أو رسم تخطيطي',
  "Widgets are placed freely over it and may overlap. Use each widget's Layer to decide what sits in front.": 'توضع العناصر فوقها بحرية وقد تتداخل. استخدم «الطبقة» لكل عنصر لتحديد ما يظهر في المقدمة.',
  'Place inside container': 'ضعه داخل حاوية',
  '— on the page —': '— على الصفحة —',
  'Layer': 'الطبقة',
  'Higher sits in front. Leave empty for the default.': 'الأعلى يظهر في المقدمة. اتركه فارغًا للقيمة الافتراضية.',
  'Control type': 'نوع عنصر التحكم',
  'Auto (by value count)': 'تلقائي (حسب عدد القيم)',
  'Button bar': 'شريط أزرار',
  'Checkbox list': 'قائمة مربعات اختيار',
  'Drop-down (multi)': 'قائمة منسدلة (متعدد)',
  'Searchable list': 'قائمة قابلة للبحث',
  'Text input (type a value)': 'إدخال نص (اكتب قيمة)',
  'Number range (from – to)': 'نطاق رقمي (من – إلى)',
  'Auto picks by how many values there are: buttons under 5, a list up to 10, a searchable list beyond. A number column with more than 20 values gets a from – to range.': 'يختار التلقائي حسب عدد القيم: أزرار لأقل من 5، وقائمة حتى 10، وقائمة قابلة للبحث لما بعدها. والعمود الرقمي الذي فيه أكثر من 20 قيمة يُعرض كنطاق من – إلى.',

  // Actions
  'Button action': 'إجراء الزر',
  '— none —': '— بلا —',
  'Navigate to page': 'الانتقال إلى صفحة',
  'Apply bookmark': 'تطبيق إشارة مرجعية',
  'Open external URL': 'فتح رابط خارجي',
  'Go to another report': 'الانتقال إلى تقرير آخر',
  'Set a parameter': 'تعيين معامل',
  'Target page': 'الصفحة الهدف',
  'The reader arrives on the target page filtered the way they left this one': 'يصل القارئ إلى الصفحة الهدف بنفس التصفية التي ترك بها هذه الصفحة',
  "Carry the reader's selections to that page": 'انقل اختيارات القارئ إلى تلك الصفحة',
  'Target URL': 'الرابط الهدف',
  'Opens in a new tab. Only http(s) links are allowed.': 'يُفتح في علامة تبويب جديدة. يُسمح بروابط http(s) فقط.',
  'Target report ID': 'رقم التقرير الهدف',
  "The number in the report's URL: /reports/12. Viewers keep their own permissions on the target.": 'الرقم في رابط التقرير: ‎/reports/12. يحتفظ المشاهدون بصلاحياتهم الخاصة على التقرير الهدف.',
  'Parameter name': 'اسم المعامل',
  'e.g. threshold': 'مثل: threshold',
  'Value to set': 'القيمة المطلوب تعيينها',
  'Clicking the button sets this report parameter for the viewer, refreshing every widget that uses it.': 'النقر على الزر يعيّن معامل التقرير هذا للمشاهد، فيُحدَّث كل عنصر يستخدمه.',
  'Target bookmark': 'الإشارة المرجعية الهدف',

  // Data & aggregation
  'Group dates by': 'تجميع التواريخ حسب',
  'each date': 'كل تاريخ',
  'hour': 'ساعة',
  'hour of day (00–23)': 'ساعة اليوم (00–23)',
  'Hijri month (هجري)': 'الشهر الهجري',
  'Hijri year (هجري)': 'السنة الهجرية',
  'fiscal quarter': 'ربع السنة المالية',
  'fiscal year': 'السنة المالية',
  'Fiscal year starts in': 'تبدأ السنة المالية في',
  "Labelled FY2025/26 and FY2025/26-Q1 (FY2025 when the year starts in January). Admin → Calendar sets the organisation's month.": 'تُسمّى FY2025/26 وFY2025/26-Q1 (وFY2025 عندما تبدأ السنة في يناير). يحدد المسؤول شهر المؤسسة من الإدارة ← التقويم.',
  "Tabular Hijri calendar: may differ by a day from Umm al-Qura at a month's start.": 'التقويم الهجري الجدولي: قد يختلف بيوم عن تقويم أم القرى في بداية الشهر.',
  'Name:': 'الاسم:',
  'Aggregation:': 'التجميع:',
  'Every measure on this chart uses it.': 'تستخدمه كل المقاييس في هذا المخطط.',
  'Same as first measure': 'مثل المقياس الأول',
  '✎ Edit hierarchy': '✎ تعديل التسلسل الهرمي',
  'Bar layout': 'تخطيط الأعمدة',
  'Clustered': 'متجاورة',
  'Stacked': 'مكدسة',
  '100% Stacked': 'مكدسة 100%',
  'Hierarchy source': 'مصدر التسلسل الهرمي',
  'Level columns': 'أعمدة المستويات',
  'Parent-child': 'أب-ابن',
  'Levels — click in order, outer first (max {n})': 'المستويات — انقر بالترتيب، الخارجي أولًا (بحد أقصى {n})',
  'ID column': 'عمود المعرّف',
  '— choose —': '— اختر —',
  'Parent column': 'عمود الأب',
  'Label column (optional)': 'عمود التسمية (اختياري)',
  '— use the ID —': '— استخدم المعرّف —',
  'A row whose parent is missing becomes a root, so a hierarchy you can only partly see still renders.': 'الصف الذي يغيب أبوه يصبح جذرًا، فيظهر التسلسل الهرمي حتى لو كنت ترى جزءًا منه فقط.',
  'This chart draws each value as a share of its parent, so only adding-up aggregations are offered.': 'يرسم هذا المخطط كل قيمة كحصة من أبيها، لذا لا تُعرض إلا طرق التجميع القابلة للجمع.',
  'Facet by': 'التقسيم حسب',
  '— choose a column —': '— اختر عمودًا —',
  'Panel chart type': 'نوع مخطط اللوحة',
  'Max panels (1–{n})': 'أقصى عدد للوحات (1–{n})',
  'Every panel shares one scale — comparing them is the point.': 'كل اللوحات تشترك في مقياس واحد — فالمقارنة بينها هي الهدف.',
  'Periods ahead ({min}–{max})': 'الفترات القادمة ({min}–{max})',
  'Node size': 'حجم العقدة',
  'Degree — how many it connects to': 'الدرجة — عدد ما تتصل به',
  'Closeness — how near it is to everything': 'القرب — مدى قربها من كل شيء',
  'Betweenness — how much traffic must pass through it': 'البينية — مقدار ما يجب أن يمر عبرها',
  'Reach — how much of the network it can get to': 'الوصول — مقدار ما تبلغه من الشبكة',
  'Reach target': 'هدف الوصول',
  'Answers when the projection reaches this value, with the range its confidence interval allows. Leave empty for no target.': 'يجيب متى يبلغ التوقع هذه القيمة، مع المدى الذي يسمح به فاصل الثقة. اتركه فارغًا لعدم تحديد هدف.',
  'Forecast method': 'طريقة التنبؤ',
  'AutoETS (StatsForecast)': 'AutoETS (StatsForecast)',
  'Simple smoothing': 'تمهيد بسيط',
  'Analytics': 'التحليلات',
  'Show average line': 'إظهار خط المتوسط',
  'Reference line value': 'قيمة الخط المرجعي',
  'Reference line label': 'تسمية الخط المرجعي',
  'Target': 'الهدف',
  'Color': 'اللون',
  'Aggregation': 'التجميع',
  '{agg} of {measure}': '{agg} لـ {measure}',
  '{agg} (row count)': '{agg} (عدد الصفوف)',
  'Rows in label order': 'الصفوف بترتيب التسميات',
  'Dates in time order, everything else by value': 'التواريخ بترتيبها الزمني، وغيرها حسب القيمة',
  // Aggregations (types/report.ts AGGREGATIONS) and their groups
  'Numeric': 'رقمي', 'Count': 'العدد', 'Statistical': 'إحصائي',
  'Sum': 'المجموع', 'None (row values)': 'بلا (قيم الصفوف)', 'Average': 'المتوسط', 'Median': 'الوسيط',
  'Min': 'الأدنى', 'Max': 'الأعلى', 'Std Deviation': 'الانحراف المعياري', 'Variance': 'التباين',
  'Range': 'المدى', 'P25': 'P25', 'P75': 'P75', 'P90': 'P90', 'P95': 'P95',
  'Count Distinct': 'عدد القيم المميزة', 'Frequency': 'التكرار', 'Percentage %': 'النسبة المئوية %',
  'Standard Error': 'الخطأ المعياري', 'Coefficient of Variation': 'معامل الاختلاف', 'Skewness': 'الالتواء',
  'Kurtosis': 'التفلطح', 'Uncorrected Sum of Squares': 'مجموع المربعات غير المصحح',
  'Corrected Sum of Squares': 'مجموع المربعات المصحح', 'T Statistic (mean = 0)': 'إحصاءة T (المتوسط = 0)',
  'P-value (for T statistic)': 'القيمة الاحتمالية (لإحصاءة T)',
  'Use {name}': 'استخدم {name}',
  'Aggregation · second measure': 'التجميع · المقياس الثاني',
  'Same as above': 'مثل أعلاه',
  'Running metric': 'مقياس تراكمي',
  'Visible columns': 'الأعمدة الظاهرة',

  // Lattice & animation
  'Repeat this chart once per value — a grid of panels on one shared axis, so panels compare honestly.': 'كرّر هذا المخطط لكل قيمة — شبكة لوحات على محور مشترك واحد لتكون المقارنة عادلة.',
  'Rows': 'الصفوف',
  'Lattice rows': 'صفوف الشبكة',
  'Columns': 'الأعمدة',
  'Lattice columns': 'أعمدة الشبكة',
  'Up to 8 rows × 8 columns (60 panels), the values with the most rows first; anything cut is named under the chart.': 'حتى 8 صفوف × 8 أعمدة (60 لوحة)، والقيم الأكثر صفوفًا أولًا؛ ويُذكر ما حُذف تحت المخطط.',
  'Play this chart through an ordered field — a date, a year — one frame per value, on one fixed axis.': 'شغّل هذا المخطط عبر حقل مرتب — تاريخ أو سنة — إطار لكل قيمة على محور ثابت واحد.',
  'Play through': 'التشغيل عبر',
  'Animate by': 'التحريك حسب',
  '— off —': '— متوقف —',
  'One frame per': 'إطار واحد لكل',
  'Animation step': 'خطوة التحريك',
  'date': 'تاريخ',

  // Filters
  "This object's own row filters — applied before aggregation, on top of dataset filters and cross-filters.": 'عوامل تصفية الصفوف الخاصة بهذا العنصر — تُطبّق قبل التجميع، إضافةً إلى عوامل تصفية مجموعة البيانات والتصفية المتقاطعة.',
  '— column —': '— عمود —',
  'relative date': 'تاريخ نسبي',
  '+ Add filter': '+ إضافة عامل تصفية',

  // Sort & limit
  'Sort order': 'ترتيب الفرز',
  'Descending': 'تنازلي',
  'Ascending': 'تصاعدي',
  'Sort by': 'الفرز حسب',
  'Automatic': 'تلقائي',
  'By Value': 'حسب القيمة',
  'By Name': 'حسب الاسم',
  'Sort column (overrides sort by)': 'عمود الفرز (يتجاوز «الفرز حسب»)',
  '— use sort by above —': '— استخدم «الفرز حسب» أعلاه —',
  'Multi-column sort (priority order)': 'فرز بعدة أعمدة (حسب الأولوية)',
  'Asc': 'تصاعدي',
  'Desc': 'تنازلي',
  '+ Add sort column': '+ إضافة عمود فرز',
  'Rows sort by the first column, ties broken by the next. Supersedes the single sort column above.': 'تُفرز الصفوف حسب العمود الأول، ويحسم العمود التالي التعادل. يحل محل عمود الفرز الواحد أعلاه.',
  'Row limit': 'حد الصفوف',
  'All (full data)': 'الكل (البيانات كاملة)',
  'Auto-reload (seconds)': 'إعادة التحميل التلقائي (ثوانٍ)',
  'off': 'متوقف',
  'Auto-reload seconds': 'ثواني إعادة التحميل التلقائي',
  "Refetches this widget's data on the interval. Minimum 5s; blank turns it off.": 'يعيد جلب بيانات هذا العنصر على فترات. الحد الأدنى 5 ثوانٍ؛ والفراغ يوقفه.',
  'Custom order (comma-separated)': 'ترتيب مخصص (مفصول بفواصل)',
  'e.g. Low, Medium, High': 'مثل: Low, Medium, High',
  'Custom category order': 'ترتيب الفئات المخصص',
  'Categories listed here come first, in this order; the rest follow. Overrides the sort above.': 'تأتي الفئات المذكورة هنا أولًا بهذا الترتيب، ثم البقية. يتجاوز الفرز أعلاه.',
  'Filter aggregated values': 'تصفية القيم المجمّعة',
  '— no filter —': '— بلا تصفية —',
  'greater than': 'أكبر من',
  'at least': 'على الأقل',
  'less than': 'أقل من',
  'at most': 'على الأكثر',
  'equal to': 'يساوي',
  'Aggregate filter value': 'قيمة تصفية التجميع',
  'value': 'القيمة',
  'Applies to the aggregated value of each category — e.g. keep regions whose total exceeds 1000.': 'تُطبّق على القيمة المجمّعة لكل فئة — مثل: الإبقاء على المناطق التي يتجاوز إجماليها 1000.',
  'Quick calculation': 'حساب سريع',
  'Percent of total': 'النسبة من الإجمالي',
  'Difference from previous': 'الفرق عن السابق',
  'Percent change from previous': 'نسبة التغير عن السابق',
  'Rank (1 = largest)': 'الترتيب (1 = الأكبر)',
  'Suppress small groups': 'إخفاء المجموعات الصغيرة',
  'minimum rows per group (off)': 'أقل عدد صفوف لكل مجموعة (متوقف)',
  'Also hide the smallest surviving group (blocks back-computation)': 'أخفِ أيضًا أصغر مجموعة متبقية (يمنع الاستنتاج العكسي)',
  'Hides any category aggregated from fewer rows than this — confidentiality suppression for small cells.': 'يُخفي أي فئة مجمّعة من صفوف أقل من هذا العدد — حجب سري للخلايا الصغيرة.',
  'Bins': 'الفئات',
  'Baseline': 'خط الأساس',
  'Fit Line': 'خط الملاءمة',
  'Linear': 'خطي',
  'Quadratic': 'تربيعي',
  'Cubic': 'تكعيبي',
  'Best Fit': 'الأفضل ملاءمة',
  'Target value (fixed, optional)': 'القيمة الهدف (ثابتة، اختيارية)',
  'leave blank to use Target column': 'اتركه فارغًا لاستخدام عمود الهدف',
  'Animation value': 'قيمة التحريك',
  'Animation value position': 'موضع قيمة التحريك',
  '— hidden —': '— مخفي —',
  'Frame order': 'ترتيب الإطارات',
  'Order: ascending': 'الترتيب: تصاعدي',
  'Order: descending': 'الترتيب: تنازلي',
  'Animation value size': 'حجم قيمة التحريك',
  'size px': 'الحجم px',
  'Animation value style': 'نمط قيمة التحريك',
  'Bold': 'عريض',
  'Normal': 'عادي',
  'Italic': 'مائل',
  'Animation value opacity': 'شفافية قيمة التحريك',
  'opacity': 'الشفافية',
  'Contrast box behind the value': 'مربع تباين خلف القيمة',
  'Gauge shape': 'شكل المقياس',
  'Arc (half donut)': 'قوس (نصف حلقة)',
  'Speedometer (dial + needle)': 'عداد سرعة (قرص + إبرة)',
  'Bullet (bar + target tick)': 'رصاصي (شريط + علامة هدف)',
  'Thermometer': 'ميزان حرارة',
  'Progress bar': 'شريط تقدم',

  // Ranking
  'Rank': 'الترتيب',
  '— all values —': '— كل القيم —',
  'Top N': 'أعلى N',
  'Bottom N': 'أدنى N',
  'Rank count': 'عدد الترتيب',
  'N or @parameter': 'N أو ‎@معامل',
  'N is a percent of categories': 'N نسبة مئوية من الفئات',
  'Bucket the rest as “All Other”': 'اجمع الباقي تحت «أخرى»',
  'Selected by aggregated value, shown in the sort order above. Ties at the boundary are kept. “All Other” aggregates the excluded categories’ raw rows.': 'يُختار حسب القيمة المجمّعة ويُعرض بترتيب الفرز أعلاه. يُحتفظ بالقيم المتعادلة عند الحد. وتجمع «أخرى» الصفوف الأصلية للفئات المستبعدة.',

  // Formatting
  'X axis label': 'تسمية المحور السيني',
  '(none)': '(بلا)',
  'Y axis label': 'تسمية المحور الصادي',
  'Right axis label': 'تسمية المحور الأيمن',
  'Tick size': 'حجم العلامات',
  'Tick colour': 'لون العلامات',
  'Category label angle': 'زاوية تسمية الفئات',
  'Automatic (fit to the labels)': 'تلقائي (حسب التسميات)',
  'Horizontal': 'أفقي',
  'Tilted 30°': 'مائل 30°',
  'Tilted 45°': 'مائل 45°',
  'Vertical': 'عمودي',
  'Value label angle': 'زاوية تسمية القيم',
  'Automatic (upright)': 'تلقائي (قائم)',
  'Show axis line': 'إظهار خط المحور',
  'Show tick marks': 'إظهار علامات التدريج',
  'Y axis scale': 'مقياس المحور الصادي',
  'Logarithmic': 'لوغاريتمي',
  'A log axis cannot show zero or negative values; the axis falls back to linear when the data contains one.': 'لا يعرض المحور اللوغاريتمي الصفر أو القيم السالبة؛ ويعود المحور خطيًا إذا احتوت البيانات على أي منها.',
  'Y axis min': 'أدنى قيمة للمحور الصادي',
  'auto': 'تلقائي',
  'Y axis max': 'أعلى قيمة للمحور الصادي',
  'Show gridlines': 'إظهار خطوط الشبكة',
  'Gridline style': 'نمط خطوط الشبكة',
  'Dashed': 'متقطع',
  'Solid': 'متصل',
  'Gridline colour': 'لون خطوط الشبكة',
  'Wall colour': 'لون الخلفية',
  'Show legend': 'إظهار وسيلة الإيضاح',
  'Legend position': 'موضع وسيلة الإيضاح',
  'Top': 'أعلى',
  'Bottom': 'أسفل',
  'Left': 'يسار',
  'Right': 'يمين',
  'Legend title': 'عنوان وسيلة الإيضاح',
  'e.g. Customer Age Group': 'مثل: الفئة العمرية للعملاء',
  'Names the FIELD the entries are values of — the swatches already say which value each colour is.': 'يسمّي الحقل الذي تنتمي إليه القيم — فالمربعات الملونة توضح أصلًا أي قيمة يمثلها كل لون.',
  'Overview axis (zoom brush)': 'محور النظرة العامة (فرشاة التكبير)',
  'Show data labels': 'إظهار تسميات البيانات',
  'Distinguish groups by pattern (accessible)': 'تمييز المجموعات بالنقش (لسهولة الوصول)',
  'Show as table (accessible alternative)': 'العرض كجدول (بديل لسهولة الوصول)',
  'Show totals': 'إظهار الإجماليات',
  'Show row subtotals': 'إظهار المجاميع الفرعية للصفوف',
  'Totals placement': 'موضع الإجماليات',
  'Before the data': 'قبل البيانات',
  'After the data': 'بعد البيانات',
  'Total covers': 'يشمل الإجمالي',
  'All rows': 'كل الصفوف',
  'Only the rows shown': 'الصفوف المعروضة فقط',
  'Row numbers': 'أرقام الصفوف',
  'Row lines': 'خطوط الصفوف',
  'Banded rows': 'صفوف متناوبة',
  'Condensed': 'مضغوط',
  'Row trend sparkline': 'خط اتجاه مصغر للصف',

  // Appearance
  'Background': 'الخلفية',
  'Border colour': 'لون الحدود',
  'Border width': 'عرض الحدود',
  'Corner radius': 'نصف قطر الزوايا',
  'Padding': 'الحشو',
  'Skin': 'المظهر',
  'None': 'بلا',
  'Flat': 'مسطح',
  'Raised': 'بارز',
  'Recessed': 'غائر',
  'Sheen': 'لمعان خفيف',
  'Gloss': 'لامع',
  'Matte': 'مطفأ',
  'Widget description (screen readers)': 'وصف العنصر (لقارئات الشاشة)',
  'Describes this widget for screen readers': 'يصف هذا العنصر لقارئات الشاشة',
  'Drillthrough page': 'صفحة التعمق',
  'Tooltip page': 'صفحة التلميح',
}

function fill(text: string, vars?: Record<string, string | number>): string {
  if (!vars) return text
  return text.replace(/\{(\w+)\}/g, (whole, k: string) => (vars[k] === undefined ? whole : String(vars[k])))
}

/** Translate one of the panel's English labels into the current language. */
export function panelLabel(language: string, text: string, vars?: Record<string, string | number>): string {
  return fill(language === 'ar' ? PANEL_AR[text] ?? text : text, vars)
}

export function usePanelLabel() {
  const { language } = useDirection()
  return useCallback((text: string, vars?: Record<string, string | number>) => panelLabel(language, text, vars),
    [language])
}
