"""baseline

Autogenerated snapshot of app.core.database.Base.metadata as it stood when
Alembic was adopted (T1) -- every table/column/index the ORM models declare
at that point in time, generated by diffing an empty scratch SQLite DB
against the metadata (see backend/alembic/README.md). Not hand-written:
regenerate rather than hand-edit if it ever needs to change.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-27 04:27:47.812837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.Column('allow_llm_sampling', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_source', sa.String(length=20), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_epoch', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_idps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=1000), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_idps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_idps_email_domain'), ['email_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_idps_org_id'), ['org_id'], unique=True)

    op.create_table('org_mcp_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_mcp_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_mcp_access_org_id'), ['org_id'], unique=True)

    op.create_table('org_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('parent_org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_parents_org_id'), ['org_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_org_parents_parent_org_id'), ['parent_org_id'], unique=False)

    op.create_table('org_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_themes_org_id'), ['org_id'], unique=False)

    op.create_table('page_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_templates_org_id'), ['org_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_org_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saml_authn_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('acs_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('col_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculated_columns', sa.JSON(), nullable=True),
    sa.Column('column_formats', sa.JSON(), nullable=True),
    sa.Column('measures', sa.JSON(), nullable=True),
    sa.Column('column_meta', sa.JSON(), nullable=True),
    sa.Column('default_filter_expr', sa.Text(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(length=500), nullable=True),
    sa.Column('source_query', sa.Text(), nullable=True),
    sa.Column('query_model', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(length=20), server_default='import', nullable=False),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('description_source', sa.String(length=20), nullable=True),
    sa.Column('last_profiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('maps_to_object', sa.String(length=255), nullable=True),
    sa.Column('maps_to_column', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_terms_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_glossary_terms_org_id'), ['org_id'], unique=False)

    op.create_table('schema_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schema_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_versions_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_versions_org_id'), ['org_id'], unique=False)

    op.create_table('source_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('row_count_estimate', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_source', sa.String(length=20), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_profiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_timed_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'schema_name', 'name', name='uq_source_object')
    )
    with op.batch_alter_table('source_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_objects_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_objects_org_id'), ['org_id'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_org_id'), ['org_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_org_id'), ['org_id'], unique=False)

    op.create_table('column_security_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('denied_columns', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('column_security_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_security_rules_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('dataset_ids', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_state', sa.String(length=10), nullable=False),
    sa.Column('last_status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_alerts_org_id'), ['org_id'], unique=False)

    op.create_table('data_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_views_org_id'), ['org_id'], unique=False)

    op.create_table('dataset_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dtype', sa.String(length=50), nullable=False),
    sa.Column('missing_pct', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('semantic_type', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'user_id', name='uq_dataset_share')
    )
    op.create_table('hierarchy_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('aggregation', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('object_row_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_object_id'], ['source_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_object_id', 'role_id', name='uq_object_role_policy')
    )
    op.create_table('query_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('dataset_key', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('sql_hash', sa.String(length=64), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('executor', sa.String(length=20), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_runs_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_runs_org_id'), ['org_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('from_dataset_id', sa.Integer(), nullable=False),
    sa.Column('from_column', sa.String(length=255), nullable=False),
    sa.Column('to_dataset_id', sa.Integer(), nullable=False),
    sa.Column('to_column', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='declared', nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('cardinality', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['from_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('additional_dataset_ids', sa.JSON(), nullable=True),
    sa.Column('theme', sa.String(length=20), server_default='default', nullable=False),
    sa.Column('display_rules', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('row_security_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('filter_expr', sa.Text(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'dataset_id', name='uq_role_dataset_rule')
    )
    op.create_table('source_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('native_type', sa.String(length=255), nullable=True),
    sa.Column('dtype', sa.String(length=50), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('semantic_type', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_source', sa.String(length=20), nullable=True),
    sa.Column('enum_labels', sa.JSON(), nullable=True),
    sa.Column('enum_labels_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['source_object_id'], ['source_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_object_id', 'name', name='uq_source_column')
    )
    with op.batch_alter_table('source_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_columns_source_object_id'), ['source_object_id'], unique=False)

    op.create_table('source_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('from_object_id', sa.Integer(), nullable=False),
    sa.Column('from_column', sa.String(length=500), nullable=False),
    sa.Column('to_object_id', sa.Integer(), nullable=False),
    sa.Column('to_column', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='declared', nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('cardinality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_object_id'], ['source_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_object_id'], ['source_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_relationships_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_relationships_from_object_id'), ['from_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_relationships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_relationships_to_object_id'), ['to_object_id'], unique=False)

    op.create_table('watermarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('cursor_column', sa.String(length=255), nullable=True),
    sa.Column('cursor_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watermarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watermarks_dataset_id'), ['dataset_id'], unique=True)

    op.create_table('widget_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_templates_org_id'), ['org_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_column_id', sa.Integer(), nullable=True),
    sa.Column('source_column_id', sa.Integer(), nullable=True),
    sa.Column('null_ratio', sa.Float(), nullable=True),
    sa.Column('distinct_count', sa.BigInteger(), nullable=True),
    sa.Column('top_k', sa.JSON(), nullable=True),
    sa.Column('min_value', sa.Text(), nullable=True),
    sa.Column('max_value', sa.Text(), nullable=True),
    sa.Column('avg_width', sa.Integer(), nullable=True),
    sa.Column('exact', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_column_id'], ['dataset_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_column_id'], ['source_columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('column_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_column_stats_dataset_column_id'), ['dataset_column_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_column_stats_source_column_id'), ['source_column_id'], unique=True)

    op.create_table('common_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('column', sa.String(length=255), nullable=False),
    sa.Column('op', sa.String(length=10), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('common_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_common_filters_report_id'), ['report_id'], unique=False)

    op.create_table('report_capability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_capability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_capability_report_id'), ['report_id'], unique=False)

    op.create_table('report_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_classifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_classifications_report_id'), ['report_id'], unique=True)

    op.create_table('report_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('page_type', sa.String(length=20), nullable=False),
    sa.Column('prompt_column', sa.String(length=255), nullable=True),
    sa.Column('prompt_label', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('page_size', sa.String(length=20), server_default='16:9', nullable=False),
    sa.Column('custom_width', sa.Integer(), nullable=True),
    sa.Column('custom_height', sa.Integer(), nullable=True),
    sa.Column('mobile_layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('param_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_parameters_report_id'), ['report_id'], unique=False)

    op.create_table('report_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_schedules_org_id'), ['org_id'], unique=False)

    op.create_table('report_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_translations_report_id'), ['report_id'], unique=False)

    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_token_hash'), ['token_hash'], unique=True)

    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('validation_failures', sa.JSON(), nullable=True),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_role_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['report_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_role_visibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_role_visibility_page_id'), ['page_id'], unique=False)

    op.create_table('report_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['report_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_comments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_comments_report_id'), ['report_id'], unique=False)

    op.create_table('report_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['report_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_link_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_link_id', sa.Integer(), nullable=False),
    sa.Column('viewer_user_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_link_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_link_access_share_link_id'), ['share_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_link_access_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_link_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_link_access_ts'))
        batch_op.drop_index(batch_op.f('ix_share_link_access_share_link_id'))

    op.drop_table('share_link_access')
    op.drop_table('report_widgets')
    with op.batch_alter_table('report_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_comments_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_comments_org_id'))

    op.drop_table('report_comments')
    with op.batch_alter_table('page_role_visibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_role_visibility_page_id'))

    op.drop_table('page_role_visibility')
    op.drop_table('agent_steps')
    op.drop_table('agent_messages')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_token_hash'))
        batch_op.drop_index(batch_op.f('ix_share_links_report_id'))
        batch_op.drop_index(batch_op.f('ix_share_links_org_id'))

    op.drop_table('share_links')
    with op.batch_alter_table('report_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_translations_report_id'))

    op.drop_table('report_translations')
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_schedules_org_id'))

    op.drop_table('report_schedules')
    with op.batch_alter_table('report_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_parameters_report_id'))

    op.drop_table('report_parameters')
    op.drop_table('report_pages')
    with op.batch_alter_table('report_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_classifications_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_classifications_org_id'))

    op.drop_table('report_classifications')
    with op.batch_alter_table('report_capability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_capability_report_id'))

    op.drop_table('report_capability')
    with op.batch_alter_table('common_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_common_filters_report_id'))

    op.drop_table('common_filters')
    with op.batch_alter_table('column_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_stats_source_column_id'))
        batch_op.drop_index(batch_op.f('ix_column_stats_dataset_column_id'))

    op.drop_table('column_stats')
    op.drop_table('bookmarks')
    op.drop_table('agent_runs')
    with op.batch_alter_table('widget_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_templates_org_id'))

    op.drop_table('widget_templates')
    with op.batch_alter_table('watermarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watermarks_dataset_id'))

    op.drop_table('watermarks')
    with op.batch_alter_table('source_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_relationships_to_object_id'))
        batch_op.drop_index(batch_op.f('ix_source_relationships_org_id'))
        batch_op.drop_index(batch_op.f('ix_source_relationships_from_object_id'))
        batch_op.drop_index(batch_op.f('ix_source_relationships_data_source_id'))

    op.drop_table('source_relationships')
    with op.batch_alter_table('source_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_columns_source_object_id'))

    op.drop_table('source_columns')
    op.drop_table('row_security_rules')
    op.drop_table('reports')
    op.drop_table('relationships')
    with op.batch_alter_table('query_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_query_runs_data_source_id'))

    op.drop_table('query_runs')
    op.drop_table('query_examples')
    op.drop_table('object_row_policies')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_org_id'))

    op.drop_table('notifications')
    op.drop_table('hierarchy_nodes')
    op.drop_table('dataset_shares')
    op.drop_table('dataset_columns')
    with op.batch_alter_table('data_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_views_org_id'))

    op.drop_table('data_views')
    with op.batch_alter_table('data_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_alerts_org_id'))

    op.drop_table('data_alerts')
    op.drop_table('conversations')
    with op.batch_alter_table('column_security_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_security_rules_dataset_id'))

    op.drop_table('column_security_rules')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))

    op.drop_table('api_keys')
    op.drop_table('analysis_results')
    with op.batch_alter_table('admin_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_org_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_created_at'))

    op.drop_table('admin_audit')
    op.drop_table('users')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_org_id'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_data_source_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('source_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_objects_org_id'))
        batch_op.drop_index(batch_op.f('ix_source_objects_data_source_id'))

    op.drop_table('source_objects')
    with op.batch_alter_table('schema_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schema_versions_org_id'))
        batch_op.drop_index(batch_op.f('ix_schema_versions_data_source_id'))

    op.drop_table('schema_versions')
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_terms_org_id'))
        batch_op.drop_index(batch_op.f('ix_glossary_terms_data_source_id'))

    op.drop_table('glossary_terms')
    op.drop_table('datasets')
    op.drop_table('saml_authn_requests')
    op.drop_table('roles')
    with op.batch_alter_table('page_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_templates_org_id'))

    op.drop_table('page_templates')
    with op.batch_alter_table('org_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_themes_org_id'))

    op.drop_table('org_themes')
    with op.batch_alter_table('org_parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_parents_parent_org_id'))
        batch_op.drop_index(batch_op.f('ix_org_parents_org_id'))

    op.drop_table('org_parents')
    with op.batch_alter_table('org_mcp_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_mcp_access_org_id'))

    op.drop_table('org_mcp_access')
    with op.batch_alter_table('org_idps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_idps_org_id'))
        batch_op.drop_index(batch_op.f('ix_org_idps_email_domain'))

    op.drop_table('org_idps')
    op.drop_table('data_sources')
    op.drop_table('organizations')
    # ### end Alembic commands ###
