"""T3 deliveries and schedule timezone

Autogenerated against the models.py changes for T3: the new `deliveries`
table (see Delivery's docstring) and `report_schedules.timezone` (an IANA
zone the scheduler interprets calendar hour/minute in, NULL = UTC).

Revision ID: 0002_deliveries_and_schedule_timezone
Revises: 0001_baseline
Create Date: 2026-08-27 05:47:21.075870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_deliveries_tz'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('artifact_kind', sa.String(length=10), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['report_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_schedule_id'), ['schedule_id'], unique=False)

    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_report_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_org_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_created_at'))

    op.drop_table('deliveries')
    # ### end Alembic commands ###
