// Flattens the app's CSS import closure into a single stylesheet for the
// converter's cfg.cssEntry.
//
// Why this exists: cfg.cssEntry copies ONE file and does not follow @import.
// src/index.css is only a bridge - it @imports the five MCAIT token files, the
// Datalytics product theme and the font declarations, then defines the app's
// own component styles on top. Copying it alone ships a stylesheet whose every
// var(--mc-*) reference resolves to nothing, so designs render untokenised.
// cfg.tokensGlob cannot help: copyTokens() returns early unless cfg.tokensPkg
// names a package under node_modules, and these tokens live in src/styles/.
//
// Font url()s are rewritten to stay correct RELATIVE TO THIS FILE, because the
// converter resolves them against dirname(cfg.cssEntry) before copying each
// woff2 into fonts/ and rewriting the reference. Pointing them straight at
// ./fonts/ instead makes them unresolvable at that moment, and the converter
// silently drops the whole @font-face block as dead.
//
// Re-run this before every converter build (see .design-sync/NOTES.md).

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ENTRY = resolve(HERE, '../src/index.css')
const OUT = resolve(HERE, 'ds-styles.css')

const IMPORT_RX = /@import\s+url\(\s*['"]?([^'")]+)['"]?\s*\)\s*;/g
const URL_RX = /url\(\s*['"]?([^'")]+\.(?:woff2?|ttf|otf))['"]?\s*\)/gi

// Every Datalytics token is scoped under [data-product="datalytics"], which the
// app stamps on <html> in index.html. Nothing outside the app does that, so a
// design built from this system would resolve var(--mc-accent) to nothing and
// render off-brand with no error anywhere. Each such selector therefore gets a
// :root-anchored twin, making the product theme the default while the original
// attribute scoping keeps working unchanged. Equal specificity, identical
// declarations - when the attribute IS present both match and agree.
const PRODUCT_SEL = '[data-product="datalytics"]'
const SELECTOR_RX = /([^{}]*)\{/g

function defaultProductTheme(css) {
  return css.replace(SELECTOR_RX, (whole, chunk) => {
    // The capture runs back to the previous brace, so it usually carries a
    // leading comment. Only the text after the last comment close is selector;
    // keep the prefix byte-for-byte.
    const cut = chunk.lastIndexOf('*/')
    const prefix = cut === -1 ? '' : chunk.slice(0, cut + 2)
    const sel = cut === -1 ? chunk : chunk.slice(cut + 2)
    if (!sel.includes(PRODUCT_SEL)) return whole
    const indent = sel.match(/^\s*/)[0]
    const twins = sel
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .flatMap((s) => (s.includes(PRODUCT_SEL) ? [s.split(PRODUCT_SEL).join(':root'), s] : [s]))
    return `${prefix}${indent}${twins.join(',\n' + indent)} {`
  })
}

// Re-base a font reference from the file it was written in onto this script's
// output location; remote and data: URLs are left exactly as they are.
function rewriteFontUrls(css, dir) {
  return css.replace(URL_RX, (whole, ref) => {
    if (/^(https?:|data:)/.test(ref)) return whole
    const rebased = relative(dirname(OUT), resolve(dir, ref)).replace(/\\/g, '/')
    return `url('${rebased.startsWith('.') ? rebased : `./${rebased}`}')`
  })
}

const seen = new Set()

function inline(file) {
  const real = resolve(file)
  if (seen.has(real)) return `/* already inlined: ${basename(real)} */\n`
  seen.add(real)
  const dir = dirname(real)
  const css = readFileSync(real, 'utf8')
  return rewriteFontUrls(css, dir).replace(IMPORT_RX, (whole, ref) => {
    if (/^(https?:|\/\/)/.test(ref)) return whole // remote sheet - leave it
    return `\n/* ---- inlined from ${ref} ---- */\n${inline(resolve(dir, ref))}\n`
  })
}

const out = `/* Generated by .design-sync/prepare-css.mjs - do not edit.
   Flattened @import closure of src/index.css, with the Datalytics product
   theme additionally anchored at :root. Regenerate after changing any file
   under src/styles/ or src/index.css. */\n\n${defaultProductTheme(inline(ENTRY))}`

writeFileSync(OUT, out)
console.error(`prepare-css: ${seen.size} files -> ds-styles.css (${(out.length / 1024).toFixed(0)} KB)`)
